version: "3.9"

services:
  redis:
    image: redis:7.4
    ports: ["6379:6379"]

  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: soar
      POSTGRES_PASSWORD: soar
      POSTGRES_DB: soar
    ports: ["5432:5432"]
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  anomaly_api:
    build: ../services/anomaly_api
    environment:
      REDIS_URL: redis://redis:6379/0
    ports: ["8001:8000"]
    depends_on: [redis]

  playbook_agent:
    build: ../services/playbook_agent
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://soar:soar@db:5432/soar
      CACAO_SCHEMA_REPO: cyentific-rni/cacao-json-schemas
      CACAO_SCHEMA_BRANCH: cacao-v2.0-cs01
      CACAO_SCHEMA_PATH: schemas/playbook.json
      OLLAMA_BASE_URL: http://ollama:11434
      OLLAMA_CHAT_MODEL: llama3.1:8b
      OLLAMA_EMBED_MODEL: embeddinggemma
      LLM_MODE: "ollama"
      # LLM settings (stub-friendly)
      #LLM_MODE: "stub"   # "stub" or "real"
    ports: ["8002:8000"]
    depends_on: [redis, db]

  playbook_agent_worker:
    build: ../services/playbook_agent
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://soar:soar@db:5432/soar
      CACAO_SCHEMA_REPO: cyentific-rni/cacao-json-schemas
      CACAO_SCHEMA_BRANCH: cacao-v2.0-cs01
      CACAO_SCHEMA_PATH: schemas/playbook.json
      playbook_agent_worker:
      LLM_MODE: ollama
      OLLAMA_BASE_URL: http://host.docker.internal:11434
      OLLAMA_CHAT_MODEL: llama3.1:8b
      OLLAMA_EMBED_MODEL: embeddinggemma
      # LLM_MODE: "stub"
    command: ["python", "agent.py"]
    depends_on: [redis, db]

  approval_ui:
    build: ../services/approval_ui
    environment:
      DATABASE_URL: postgresql+psycopg://soar:soar@db:5432/soar
      AGENT_API_URL: http://playbook_agent:8000
    ports: ["8501:8501"]
    depends_on: [db, playbook_agent]

  executor_stub:
    build: ../services/executor_stub
    environment:
      REDIS_URL: redis://redis:6379/0
      DATABASE_URL: postgresql+psycopg://soar:soar@db:5432/soar
    ports: ["8003:8000"]
    depends_on: [redis, db]

# Using Ollama LLM server on host machine
#   ollama:
#     image: ollama/ollama:latest
#     ports:
#       - "11434:11434"
#     volumes:
#       - ollama:/root/.ollama
  
# volumes:
#   ollama:



  # Optional: CACAO Roaster for visual inspection (run separately too)
  # roaster:
  #   build:
  #     context: https://github.com/opencybersecurityalliance/cacao-roaster.git#main:.
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"